### ISSUE TITLE
Wrong syntax highlighting for multiline strings 

### ISSUE THREAD

**Issue by hyyan** [BBx-Kitchen/bbj-language-server#107]
The following is a valid multiline string in BBj. But you see that the syntax highlighting is wrong.

```
pos! = inputD!.executeScript("
: (async () => {
:  await customElements.whenDefined('bbj-inputd');
:  await component.setFocus();
:  await component.setSelectionRange(3,5);
:  return (await component.getPart('input')).selectionStart
:})();
:", BBjAPI.TRUE)
```

![Screenshot 2023-09-27 at 10 32 54 AM](https://github.com/BBx-Kitchen/bbj-language-server/assets/4313420/ee855314-85cd-4446-9f59-2a06706a8976)

**Comment by StephanWald** [comment]
tested, works as expected now.

**Comment by StephanWald** [comment]
**Triage → actionable** (confirmed bug). Multiline `"`/`'` strings lose their string scope when the opening quote is the **last character on the line** (the `executeScript("` case here). Root cause: the `string-character-escape` pattern ends with a zero-width `|$` alternative (`syntaxes/bbj.tmLanguage.json:71`); its zero-width match at EOL terminates the string context. Removing the `|$` alternative makes the string span continuation lines correctly — verified by running the grammar through vscode-textmate. Labeled `actionable`.

**Comment by StephanWald** [comment]
note: in BBj syntax a flavor of a multiline statement is a ":" colon at the beginning of the next line (not a trailing slash or backslash like in other languages or shells). So the following is one single line in reality:

```
PRINT
: A$
: ;
: PRINT B$
```

resolves in essence to 

```
PRINT A$; PRINT B$
```
