### ISSUE TITLE
Enter statement with no arguments 

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#121]
In `enter` statement variablen references are optionsl:
`ENTER {varname{,varname...}{,ERR=lineref}}`

Following code currently reports an error:
```js
enter
print "sdf"

rem Following should also work. Currently `foo$` is consumed as `ENTER` varname argument.
enter
foo$ = "bar"

```

**Comment by Lotes** [comment]
Oh I made this happen by coincidence. But I have one question:

@StephanWald What is the right syntax, when `ENTER` has no variables, but an `ERR` argument?
Is it
a. `ENTER, ERR=label` with a comma
b. `ENTER ERR=label` without a comma
c. the error case will never happen, since no variables are given
d. something else?

Currently it is implemented as solution `a`.

**Comment by StephanWald** [comment]
Formally, ENTER has no optional ERR= when no variables passed. It can never fail.

```
ENTER {varname{,varname...}{,ERR=lineref}}
```

It can then only apper alone

```
ENTER
```
