### ISSUE TITLE
References to extended classes cannot be resolved for code completion

### ISSUE THREAD

**Issue by mphelpsbasis** [BBx-Kitchen/bbj-language-server#171]
Code completion does not function correctly for classes that extend other classes.

Test this using the code completion example code "Sample_Classes.bbj" shown below from the BBj Documentation at
https://documentation.basis.cloud/BASISHelp/WebHelp/ide/BDT_Code_Completion.htm

rem ' Sample_Classes.bbj
class public SuperClass
    field public BBjInt superFieldInt%
    field private BBjString superFieldString$
    field protected BBjNumber superFieldNum
    method public SuperClass(BBjInt i%, BBjString s$, BBjNumber n)
        #superFieldInt% = i%
        #superFieldString$ = s$
        #superFieldNum = n
    methodend
    method protected void superProtected(BBjString s$)
        print "SuperClass protected method" + s$
    methodend
    method public static BBjInt superPublicStatic(BBjInt i%)
        methodret i%*2
    methodend
classend

class public SubClass extends SuperClass
    field private BBjString subFieldString$
    method public SubClass(BBjInt i%, BBjString s$, BBjNumber n)
        #super!(i%, s$, n)
        #subFieldString$ = s$
        #this!.superPublicStatic(5)
    methodend
classend

interface public SampleInterface
    method public void interfaceMethod()
    method private void interfaceMethodPrivate()
interfaceend

Enter the following in a new file and note that code completion does not work for instances of the SubClass, which extends the SuperClass.  The error says "Could not resolve reference to Class named 'Sample_Classes.bbjSubClass'."

use ::Sample_Classes.bbj::SampleInterface
use ::Sample_Classes.bbj::SuperClass
use ::Sample_Classes.bbj::SubClasss

declare SubClass subvar!

subvar!.

**Comment by StephanWald** [comment]
Thank you for the report. A few additions:

1. the sample sub has a typo, ```use ::Sample_Classes.bbj::SubClass```**s** has one trailing "s" too much. Once you fix that, VSCode can correctly find and address the class in the file system.
<img width="508" alt="Screenshot 2024-10-26 at 07 03 41" src="https://github.com/user-attachments/assets/7ddba480-7972-4d23-b073-f634e29e5ba0">

2. You're correctly reporting that the code assist proposes private and protected fields, while outside any inheritance scope. This bug is already addressed in #74 . I put in a cross referencing comment and we'll leave this report open until 

I'm closing this new report after adding the relevant gist to #74 . Txs for testing and reporting!
