### ISSUE TITLE
THROW verb in methods

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#46]
This is valid, THROW is resulting in the falsely flagged error on methodend:

```
class public Sample

    method public String write(String dr!)
        seterr writeErr
        PRINT dr!
        methodret dr!

        writeErr:
        throw errmes(-1), err
    methodend

classend
```

**Comment by dhuebner** [comment]
@StephanWald 
Throw Verb allows following syntax: `THROW str{,int}{,ERR=lineref}`. The example above doesn't match this definition.
https://documentation.basis.cloud/BASISHelp/WebHelp/commands/throw_verb.htm

I know we where talking a bit about weeks ago where it turned out that inside the methods the syntax is a bit different, without `=lineref`. Are there other differences? Could you point me to the corresponding documentation?

TODO
- make `'=' err=[LabelDecl]` in `ThrowStatement`
- validate if not inside a method, missing `=lineref` should be an error
- add tests

**Comment by StephanWald** [comment]
The "err" in the sample is not meant to be the "err=" clause, but is the "ERR" builtin system variable that returns an error code.

You can play with it by doing something like this in the console:
```
>lkjlkj
!ERROR=20  (Syntax Error: lkjlkj)
>? err
 20
>
```

ERR always returns the last BASIC error code. In the THROW sample it's simply used to pass on the original err code as is, instead of ERR any integer would be valid.

```
class public Sample

    method public String write(String dr!)
        seterr writeErr
        PRINT dr!
        methodret dr!

        writeErr:
        throw "There was some Error!",201
    methodend

classend
```

**Comment by dhuebner** [comment]
Fixed
